### ISSUE TITLE
Player Mozgás

### ISSUE THREAD

**Issue by felvinelover** [Felvine/EL#1]
* Alap négy irányú mozgás, de a Unity vektorokat használjuk ami alapértelmezetten tudja egy controller stick szabad mozgását. 
* Ha az alap irány inputot kapja meg a player akkor Walk animáció az aktív
* Ha nincs input Idle animáció az aktív.
* A Player karakter mindig abba az irányba áll meg amerre utóljára mozgott.
* Futásnál sebességet növelünk ami addig tart amíg a Run button le van nyomva.
* Roll inputra a karakter gurul és kényszerítetten abba az irányba amerre éppen utoljára mozgott, vagy amerre épp áll. A Roll-t nem lehet megszakítani az adott távolságot kényszerűen megteszi a karakter. (A Invanurable frame-eket nem implementáljuk M1-ben.)

**Comment by Marteen21** [comment]
Already implemented on master ab310ec14ff1644cc26597f62203f4cc0cf910e7
