### ISSUE TITLE
Player Animációk és logikájuk

### ISSUE THREAD

**Issue by felvinelover** [Felvine/EL#3]
Az animációk 2 irányúak (nem látjuka karakter hátát felfelé mozgásnál és az arcát lefelé mozgásnál). Ebben a formában elegendő csak 1 riget és animációt megcsinálni és azt tükrözni.

Animációk (inputok):

* Idle (Nincs input)
* Walk (Vector-al konfigurált nem gombbal a gamepad controllerek miatt)
* Run (Vector + Run Button konfigurálva billentyűzetre és Gamepadra)
* Attack1 (Fire 1 button)
* Attack2 (combo: Fire 1 után Fire 2)
* Attack3 (combo: Fire 1 után Fire 1)
* Attack4 (Fire 2 button)
* Roll (Roll button)

Animációk logikája:

* A támadási animációk, ha egyszer elindultak, már nem lehet megszakítani őket.
* A Roll ha el lett indítva nem lehet megszakítani
* Támadást és Roll-t lehet indítani Idle/Walk/ és Run- ból is. 
* Az Attack kombinációkat úgy kötjük össze, hogy az első animáció (Pl Attack 1) adott frame-jein lehessen leütni combo-t eredményező inputot (pl Attack 2). Ha a játékos túl hamar üti le a gombot, vagy túl későn akkor a 2. animáció nem valósul meg. Az inputot túl korai leütésnél nem tároljuk, tehát a gomb folyamatos nyomogatásával nem lehet kombót előhozni. 

A nem megszakítható Attack és Roll animációk alapvetően meghatározzák a játékmenetet. Ezzel biztosítjuk azt, hogy a harc és a pozícionálás a skill based játékmenet szerves része legyen. A játékosnak döntéseket kell hoznia, hogy egy adott támadás erejéig (animáció hossza) vállalja e, hogy sebezhető (hiszen nem tud mozdulni, vagy rosszkor tér ki).

**Comment by Marteen21** [comment]
Nagy része implementálva.
A kimaradt részeket áthelyeztem külön külön issue-kba.
#17 
#16
