### ISSUE TITLE
Sprite-ok szétesnek

### ISSUE THREAD

**Issue by Marteen21** [Felvine/EL#34]
a4b0624dcfd11a55af3641c091e4385a8f606d15 -al betettem egy nagyon szimpla viselkedést a kutyusnak (követi a játékost) viszont amint elindul a walk animáció szétesnek a sprite-ok.

Repro: sétálj el pár lépést a kutyától

![image](https://user-images.githubusercontent.com/6805260/30940921-3ebe59ac-a3e3-11e7-9781-791fd162461a.png)

**Comment by felvinelover** [comment]
Szóval nem igazán tudom mi a méretes krómcső történik a sprite-okkal...
Fel commit-oltam egy verziót DEV-re FIX álnév alatt, majd kapd le és csekkold, elméletileg működik.
A helyzet az hogy lefrissítettem a Unity-t, benyitottam az EL DEV-et és az animációban szét voltak hullva azok a sprite-ok amik hibásak voltak. vissza raktam őket a helyükre és azóta működnek. Egy kivétel van a bal alsó lábszár ami nem áll be fix rossz pozícióra, de egy pár tized másodperccel később ugrik vissza a helyére. Arra tippelnék hogy Unity bug-ról van szó. Ami biztos hogy a hierarchiába foglalás megoldja a problémát, de utólag már nem lehet átdolgozni az animációkat hierarchikusra, csak ha kb. előröl kezdem. Jó tapasztalat ez mert a player character animációi nem problémásak és ott teljes hierarchia van. A jövőben gondolunk erre, még nézegetem mi lehet.
