### ISSUE TITLE
Training Dummy

### ISSUE THREAD

**Issue by felvinelover** [Felvine/EL#5]
* Training dummy-nak egy egyszerű Health rendszere lesz. Csak sebzéseket kap és ilyenkor lejátszunk egy animációt (Training Dummy Hit), amit egy következő támadás újraindít.
* A Training Dummy-ra számolunk sebzést, a sebzést a kard változója adja, a sebzés mértéke a kard tulajdonsága (meg kell vizsgálni hol lenne a legjobb tárolni. Gondolkodjunk előre hol lenne a jobb).
* A sebzés mértékét egy lebegő, majd eltűnő számmal írjuk ki a Training Dummy főlé (valami beépített számok is jók lesznek, mert valószínű nem lesznek ilyen lebegő számok a Tech Demo-ban sem már).

**Comment by Marteen21** [comment]
Implemented on dev branch
a8bbda0fff5bc1ec7f3d316cab96fe421104f4a1
